const bottles = {
    "Aglianico": "red-2",
    "Albariño": "white-2",
    "Alvarinho": "white-2",
    "Arinto": "red-1",
    "Arneis": "white-1",
    "Barbera": "red-1",
    "Blaufränkisch": "red-1",
    "Bonarda": "red-1",
    "Bordeaux-style Red Blend": "red-1",
    "Bordeaux-style White Blend": "red-1",
    "Cabernet Blend": "red-1",
    "Cabernet Franc": "red-1",
    "Cabernet Sauvignon": "red-1",
    "Cabernet Sauvignon-Merlot": "red-1",
    "Cabernet Sauvignon-Syrah": "red-1",
    "Carmenère": "red-1",
    "Champagne Blend": "white-3",
    "Chardonnay": "white-2",
    "Chenin Blanc": "white-1",
    "Corvina, Rondinella, Molinara": "red-1",
    "Dolcetto": "red-3",
    "Falanghina": "white-2",
    "Fiano": "white-2",
    "Friulano": "white-1",
    "G-S-M": "red-3",
    "Gamay": "red-3",
    "Garganega": "red-1",
    "Garnacha": "red-2",
    "Gewürztraminer": "white-3",
    "Glera": "white-2",
    "Greco": "white-2",
    "Grenache": "red-2",
    "Grenache Blanc": "white-2",
    "Grillo": "white-1",
    "Grüner Veltliner": "white-1",
    "Malbec": "red-2",
    "Malbec-Merlot": "red-2",
    "Melon": "white-1",
    "Mencía": "red-1",
    "Meritage": "red-1",
    "Merlot": "red-2",
    "Monastrell": "white-1",
    "Montepulciano": "red-1",
    "Moscato": "white-1",
    "Mourvèdre": "red-3",
    "Muscat": "white-1",
    "Nebbiolo": "red-3",
    "Negroamaro": "red-2",
    "Nerello Mascalese": "red-3",
    "Nero d'Avola": "red-2",
    "Petit Verdot": "red-2",
    "Petite Sirah": "red-2",
    "Pinot Bianco": "white-1",
    "Pinot Blanc": "white-1",
    "Pinot Grigio": "white-1",
    "Pinot Gris": "white-1",
    "Pinot Nero": "red-3",
    "Pinot Noir": "red-3",
    "Pinotage": "red-2",
    "Port": "red-2",
    "Portuguese Red": "red-2",
    "Portuguese White": "white-1",
    "Primitivo": "red-2",
    "Prosecco": "white-1",
    "Red Blend": "red-1",
    "Rhône-style Red Blend": "red-1",
    "Rhône-style White Blend": "red-1",
    "Ribolla Gialla": "white-1",
    "Riesling": "white-1",
    "Rosato": "white-1",
    "Rosé": "white-1",
    "Roussanne": "white-1",
    "Sagrantino": "red-3",
    "Sangiovese": "red-1",
    "Sangiovese Grosso": "red-1",
    "Sauvignon": "white-1",
    "Sauvignon Blanc": "white-2",
    "Sherry": "red-3",
    "Shiraz": "red-2",
    "Sparkling Blend": "white-1",
    "St. Laurent": "red-1",
    "Syrah": "red-2",
    "Sémillon": "white-1",
    "Tannat": "red-2",
    "Tannat-Cabernet": "red-2",
    "Tempranillo": "red-1",
    "Tempranillo Blend": "red-1",
    "Tinta de Toro": "red-2",
    "Tinto Fino": "red-2",
    "Torrontés": "white-1",
    "Touriga Nacional": "red-2",
    "Turbiana": "red-1",
    "Verdejo": "white-1",
    "Verdicchio": "white-3",
    "Vermentino": "white-3",
    "Vernaccia": "red-1",
    "Viognier": "white-1",
    "Viura": "red-1",
    "White Blend": "white-1",
    "Zinfandel": "red-2",
    "Zweigelt": "white-3",
    "Prugnolo Gentile": "red-1",
    "Bual": "red-1",
    "Cinsault": "red-1",
    "Traminer": "white-1"
}

export default function bottlesImages(str) {
    let match = bottles[str];
    if (!match) {
        for (let b in bottles) {
            if (str.indexOf(b) > -1) {
                match = bottles[b];
                break;
            }
        }
    }
    if (!match) match = 'red-1';
    return `static/sil/${match}.png`
};